###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://www.project-piper.io/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###

### General project setup
general:
  buildTool: "mta"

### Step-specific configuration
steps:
artifactPrepareVersion:
    versioningType: cloud_noTag
npmExecuteLint:
    failOnError: true
cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

### Stage-specific configuration
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
Release:
   cloudFoundryDeploy: true
   cfTargets:
     - org: '4aa88d79trial'
       space: 'dev'
       apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
       appName: 'capapp'
       credentialsId: 'deploy-cf-cred'
